[2025-02-23T04:31:16.212+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-23T04:31:16.252+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2025-02-23T04:31:16.273+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.first_task scheduled__2022-07-02T00:00:00+00:00 [queued]>
[2025-02-23T04:31:16.275+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-02-23T04:31:16.332+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): first_task> on 2022-07-02 00:00:00+00:00
[2025-02-23T04:31:16.345+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2569) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-23T04:31:16.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'first_task', 'scheduled__2022-07-02T00:00:00+00:00', '--job-id', '518', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmptnsm_lg9']
[2025-02-23T04:31:16.348+0000] {standard_task_runner.py:72} INFO - Started process 2579 to run task
[2025-02-23T04:31:16.349+0000] {standard_task_runner.py:105} INFO - Job 518: Subtask first_task
[2025-02-23T04:31:16.444+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag.first_task scheduled__2022-07-02T00:00:00+00:00 [running]> on host f66dd6409c88
[2025-02-23T04:31:16.630+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vn5705j' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2022-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-07-02T00:00:00+00:00'
[2025-02-23T04:31:16.632+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-23T04:31:16.666+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-23T04:31:16.668+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Hello World!' This is the first Task"]
[2025-02-23T04:31:16.687+0000] {subprocess.py:99} INFO - Output:
[2025-02-23T04:31:16.689+0000] {subprocess.py:106} INFO - Hello World! This is the first Task
[2025-02-23T04:31:16.690+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-23T04:31:16.739+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-23T04:31:16.741+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=first_task, run_id=scheduled__2022-07-02T00:00:00+00:00, execution_date=20220702T000000, start_date=20250223T043116, end_date=20250223T043116
[2025-02-23T04:31:16.807+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-23T04:31:16.839+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-23T04:31:16.842+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
